#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_ENABLED_PATH/common/functions"
APP="$1"
verify_app_name "$APP"
IMAGE=$(get_app_image_name $APP)
FILE_ROOT="$DOKKU_ROOT/$APP/DOKKU_BUILD_FILES"

DOCKER_BIN="${DOCKER_BIN:=docker}"

if [[ -d "$FILE_ROOT" ]]; then
  dokku_log_info1 "Adding build files to build environment ..."
  shopt -s dotglob # include hidden files
  for path in "$FILE_ROOT/"**; do
    target_path="/app/${path#$FILE_ROOT/}"  # Extract relative path
    if [[ -d "$path" ]]; then
      dokku_log_verbose "- Creating directory: $target_path"
      "$DOCKER_BIN" run -i "$IMAGE" mkdir -p "$target_path"
    else
      dokku_log_verbose "- Copying file: $target_path"
      id=$("$DOCKER_BIN" run -i -a stdin "$IMAGE" /bin/bash -c "cat > '$target_path' " < "$path")
      test "$("$DOCKER_BIN" wait $id)" -eq 0
      "$DOCKER_BIN" commit $id $IMAGE > /dev/null
      "$DOCKER_BIN" stop $id > /dev/null 2>&1 || true
      "$DOCKER_BIN" kill $id > /dev/null 2>&1 || true
    fi
  done
fi
